// frontend/src/components/ChatMessage.vue
<template>
    <div
        class="message"
        :class="{
            'user-message': message.sender === 'user',
            'bot-message': message.sender === 'assistant',
            typing: message.isTyping,
            'appear-animation': message.animationState === 'appear',
        }"
    >
        <!-- 내 메시지는 오른쪽에 글씨만 (아바타·상자 없음). 에이전트 답변에만 아바타를 둔다 -->
        <div v-if="message.sender !== 'user'" class="message-avatar">
            <div class="avatar bot-avatar">
                <img src="@/assets/agent-logo.png" alt="Assistant" />
            </div>
        </div>

        <div class="message-content-wrapper">
            <!-- 답변을 만들며 부른 도구: 왼쪽 세로줄 목록. 실패는 색이 아니라 모양(— 와 굵기)으로 구분한다 -->
            <ol
                v-if="message.sender === 'assistant' && steps.length"
                class="tool-trace"
                aria-label="사용한 도구"
            >
                <li
                    v-for="(step, index) in steps"
                    :key="index"
                    class="tool-step"
                    :class="{ failed: step.failed }"
                    :title="step.name"
                >
                    <span class="tool-step-title"
                        >{{ step.failed ? '—' : '✓' }} {{ step.label
                        }}<template v-if="step.failed"> — 실패</template></span
                    >
                    <span v-if="step.detail" class="tool-step-detail">{{ step.detail }}</span>
                    <span v-if="step.error" class="tool-step-detail tool-step-error">{{
                        step.error
                    }}</span>
                </li>
            </ol>

            <div v-if="message.isTyping" class="typing-indicator">
                <span class="dot"></span>
                <span class="dot"></span>
                <span class="dot"></span>
            </div>
            <div
                v-else
                class="message-content markdown-content"
                v-html="formatMessageContent(message.displayText || message.text)"
            ></div>

            <div v-if="message.elapsed_time || message.inference" class="query-metadata">
                <div v-if="message.elapsed_time" class="elapsed-time">
                    실행 시간: {{ message.elapsed_time }}
                </div>

                <div class="details-toggle" @click="toggleDetails">
                    <span>{{ showDetails ? '간략히 보기' : '자세히 보기' }}</span>
                    <span class="toggle-icon">{{ showDetails ? '▲' : '▼' }}</span>
                </div>

                <div v-if="showDetails" class="query-details">
                    <div v-if="message.query_string" class="query-section">
                        <h4>SQL 쿼리</h4>
                        <pre
                            class="sql-query"
                        ><code v-html="formatSqlQuery(message.query_string)"></code></pre>
                    </div>

                    <div
                        v-if="message.query_result && message.query_result.length > 0"
                        class="query-section"
                    >
                        <h4>쿼리 결과</h4>
                        <div class="query-result-table-container">
                            <table class="query-result-table">
                                <thead>
                                    <tr>
                                        <th v-for="(_, key) in message.query_result[0]" :key="key">
                                            {{ key }}
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr
                                        v-for="(row, rowIndex) in message.query_result"
                                        :key="rowIndex"
                                    >
                                        <td v-for="(value, key) in row" :key="`${rowIndex}-${key}`">
                                            {{
                                                typeof value === 'string'
                                                    ? value.replace(/\\n/g, ' ')
                                                    : value
                                            }}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div v-if="message.inference" class="query-section">
                        <h4>추론 데이터</h4>
                        <pre
                            class="inference-data"
                        ><code v-html="formatInferenceData(message.inference)"></code></pre>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
    import type { PropType } from 'vue';
    import { computed, defineComponent, ref } from 'vue';
    import { parseMarkdown } from '@/utils/markdown';
    import { toolSteps } from '@/utils/toolTrace';
    import type { ChatMessageType } from '@/types/chat.ts';

    export default defineComponent({
        name: 'ChatMessage',

        props: {
            message: {
                type: Object as PropType<ChatMessageType>,
                required: true,
            },
        },

        setup(props) {
            const showDetails = ref(false);
            const steps = computed(() => toolSteps(props.message.inference));

            const toggleDetails = () => {
                showDetails.value = !showDetails.value;
            };

            const formatSqlQuery = (sql: string | any) => {
                if (!sql) return '';

                return sql
                    .replace(
                        /\b(SELECT|FROM|WHERE|JOIN|LEFT|RIGHT|INNER|OUTER|GROUP BY|ORDER BY|HAVING|LIMIT|OFFSET|AS|ON|AND|OR|NOT|IN|BETWEEN|LIKE|IS|NULL|TRUE|FALSE|DESC|ASC|COUNT|SUM|AVG|MIN|MAX|date_parse)\b/gi,
                        (match: any) => `<span class="sql-keyword">${match}</span>`,
                    )
                    .replace(/\n/g, '<br>')
                    .replace(/('[^']*')/g, `<span class="sql-string">$1</span>`);
            };

            const formatInferenceData = (inference: any): string => {
                try {
                    if (typeof inference === 'string') {
                        try {
                            const obj = JSON.parse(inference);
                            return JSON.stringify(obj, null, 2)
                                .replace(
                                    /"([^"]+)":/g,
                                    '"<span style="color: #0033b3; font-weight: bold;">$1</span>":',
                                )
                                .replace(
                                    /: "([^"]*)"/g,
                                    ': "<span style="color: #014325;">$1</span>"',
                                );
                        } catch (e) {
                            return inference;
                        }
                    }

                    const jsonStr = JSON.stringify(inference, null, 2);
                    return jsonStr
                        .replace(
                            /"([^"]+)":/g,
                            '"<span style="color: #0033b3; font-weight: bold;">$1</span>":',
                        )
                        .replace(/: "([^"]*)"/g, ': "<span style="color: #014325;">$1</span>"');
                } catch (error) {
                    console.error('Inference 데이터 포맷팅 오류:', error);
                    return String(inference);
                }
            };

            const formatMessageContent = (content: string): string => {
                if (!content) return '';

                const escapeHtml = (text: string) => {
                    return text
                        .replace(/&/g, '&amp;')
                        .replace(/</g, '&lt;')
                        .replace(/>/g, '&gt;')
                        .replace(/"/g, '&quot;')
                        .replace(/'/g, '&#039;');
                };

                const escapedContent = escapeHtml(content);

                const htmlContent = parseMarkdown(escapedContent);

                return htmlContent;
            };

            const formatMessageTime = (dateString: string): string => {
                try {
                    const date = new Date(dateString);
                    return date.toLocaleTimeString('ko-KR', {
                        hour: '2-digit',
                        minute: '2-digit',
                    });
                } catch (e) {
                    return '';
                }
            };

            return {
                formatMessageContent,
                formatMessageTime,
                formatSqlQuery,
                formatInferenceData,
                showDetails,
                toggleDetails,
                steps,
            };
        },
    });
</script>

<style scoped>
    .message {
        display: flex;
        margin-bottom: 20px;
        animation-duration: 0.3s;
        animation-fill-mode: both;
    }

    .user-message {
        animation-name: sendMessage;
        justify-content: flex-end; /* 내 메시지는 오른쪽 */
    }

    .bot-message {
        animation-name: receiveMessage;
    }

    @keyframes sendMessage {
        0% {
            opacity: 0;
            transform: translateY(10px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }

    @keyframes receiveMessage {
        0% {
            opacity: 0;
            transform: translateY(10px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .appear-animation {
        animation-name: appearMessage;
        animation-duration: 0.3s;
    }

    @keyframes appearMessage {
        0% {
            opacity: 0;
            transform: translateY(10px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .message-avatar {
        margin-right: 12px;
        align-self: flex-start;
    }

    .avatar {
        width: 36px;
        height: 36px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: bold;
        color: white;
    }


    .bot-avatar {
        background-color: #dddddd;
        overflow: hidden;
    }

    .bot-avatar img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .message-content-wrapper {
        font-size: 17px;
        flex: 1;
        max-width: calc(100% - 50px);
        overflow-wrap: break-word;
    }

    .message-content {
        padding: 8px 16px;
        border-radius: 18px;
        position: relative;
        white-space: pre-wrap;
        overflow-wrap: break-word;
        word-break: break-word;
        max-width: 100%;
        overflow-x: auto;
    }

    /* 내 메시지: 상자 없이 글씨만, 오른쪽에 붙인다. 긴 질문은 화면의 3/4까지만 쓰고 줄을 바꾼다 */
    .user-message .message-content-wrapper {
        flex: 0 1 auto;
        max-width: 75%;
    }

    .user-message .message-content {
        background: none;
        border-radius: 0;
        padding: 0;
        color: #333;
        text-align: right;
    }

    /* 답변은 말풍선 없이 본문으로 (말풍선은 내 질문에만) */
    .bot-message .message-content {
        background: none;
        border-radius: 0;
        padding: 6px 0 0; /* 첫 줄을 아바타(36px) 가운데쯤에 맞춘다 */
        color: #333;
    }

    /* 도구 호출 목록: 왼쪽 세로줄, 본문보다 작고 옅게 */
    .tool-trace {
        list-style: none;
        margin: 8px 0 12px;
        padding: 2px 0 2px 12px;
        border-left: 2px solid #dee2e6;
        font-size: 13px;
        line-height: 1.5;
        color: #6c757d;
    }

    .tool-step + .tool-step {
        margin-top: 6px;
    }

    .tool-step-title {
        display: block;
        color: #495057;
    }

    /* 입력값만 고정폭 글꼴 (고정폭 글꼴에는 한글이 없어 이름까지 쓰면 글자 간격이 벌어진다) */
    .tool-step-detail {
        display: block;
        padding-left: 1.2em; /* "✓ " 다음 글자에 맞춘다 */
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
        font-size: 12px;
        color: #868e96;
        overflow-wrap: anywhere;
    }

    /* 오류는 문장이라 본문 글꼴로 */
    .tool-step-error {
        font-family: inherit;
        font-size: 12.5px;
    }

    .tool-step.failed .tool-step-title {
        font-weight: 600;
    }

    .typing-indicator {
        display: flex;
        align-items: center;
        padding: 12px 16px;
        background-color: #f5f5f5;
        border-radius: 18px;
        border-top-left-radius: 4px;
        gap: 4px;
        height: 44px;
    }

    .dot {
        width: 8px;
        height: 8px;
        background-color: #aaa;
        border-radius: 50%;
        animation: dotPulse 1.4s infinite ease-in-out;
    }

    .dot:nth-child(1) {
        animation-delay: 0s;
    }

    .dot:nth-child(2) {
        animation-delay: 0.2s;
    }

    .dot:nth-child(3) {
        animation-delay: 0.4s;
    }

    @keyframes dotPulse {
        0%,
        60%,
        100% {
            transform: scale(0.8);
            opacity: 0.6;
        }
        30% {
            transform: scale(1.2);
            opacity: 1;
        }
    }

    :deep(.markdown-content h1) {
        font-size: 1.5rem;
        margin: 0.8rem 0;
        border-bottom: 1px solid #eee;
        padding-bottom: 0.3rem;
    }

    :deep(.markdown-content h2) {
        font-size: 1.3rem;
        margin: 0.7rem 0;
    }

    :deep(.markdown-content h3) {
        font-size: 1.1rem;
        margin: 0.6rem 0;
    }

    :deep(.markdown-content p) {
        margin: 0.5rem 0;
        max-width: 100%;
    }

    :deep(.markdown-content ul),
    :deep(.markdown-content ol) {
        padding-left: 1.5rem;
        margin: 0.5rem 0;
        line-height: inherit; /* base.css의 전역 ol { line-height: 1.0 } 때문에 번호 목록만 좁아지지 않게 */
    }

    :deep(.markdown-content li) {
        margin: 0.3rem 0;
    }

    :deep(.markdown-content code) {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 0.1rem 0.3rem;
        border-radius: 3px;
        font-family: monospace;
        font-size: 0.9em;
    }

    :deep(.markdown-content pre) {
        background-color: rgba(0, 0, 0, 0.05);
        padding: 0.8rem;
        border-radius: 4px;
        overflow-x: auto;
        margin: 0.7rem 0;
        max-width: 100%;
        white-space: pre-wrap;
    }

    :deep(.markdown-content pre code) {
        background: none;
        padding: 0;
        white-space: pre-wrap;
        word-break: break-word;
    }

    /* 마크다운 표 (utils/markdown.ts). 폭이 좁으면 표만 가로로 스크롤한다 */
    :deep(.markdown-table-container) {
        overflow-x: auto;
        margin: 8px 0 12px;
        white-space: normal; /* 본문의 pre-wrap이 칸 사이 공백을 늘리지 않게 */
    }

    :deep(.markdown-table) {
        border-collapse: collapse;
        font-size: 15px;
        line-height: 1.5;
    }

    :deep(.markdown-table th),
    :deep(.markdown-table td) {
        border: 1px solid #dee2e6;
        padding: 6px 12px;
        text-align: left;
        vertical-align: top;
    }

    :deep(.markdown-table th) {
        background-color: #f8f9fa;
        font-weight: 600;
        white-space: nowrap;
    }

    :deep(.markdown-content strong) {
        font-weight: bold;
    }

    :deep(.markdown-content em) {
        font-style: italic;
    }

    :deep(.message-content a) {
        color: #0d6efd;
        text-decoration: underline;
        word-break: break-all;
    }

    :deep(.user-message .message-content a) {
        color: #0a58ca;
    }

    :deep(.markdown-image-container) {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 1rem 0;
        width: 100%;
    }

    :deep(.markdown-image-container a) {
        display: flex;
        text-decoration: none;
        border: none;
        justify-content: center;
        align-items: center;
    }

    :deep(.markdown-image) {
        max-width: 50%;
        height: auto;
        width: auto;
        border-radius: 8px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        transition:
            transform 0.2s ease,
            box-shadow 0.2s ease;
        cursor: pointer;
        object-fit: contain;
        display: block;
    }

    :deep(.markdown-image:hover) {
        transform: scale(1.05);
        box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
    }

    @media (max-width: 768px) {
        :deep(.markdown-image) {
            max-width: 70%;
            max-height: 30vh;
        }
    }

    @media (max-width: 1024px) and (min-width: 769px) {
        :deep(.markdown-image) {
            max-width: 60%;
            max-height: 35vh;
        }
    }

    .query-metadata {
        margin-top: 10px;
        font-size: 0.85rem;
    }

    .elapsed-time {
        color: #888;
        margin-bottom: 4px;
    }

    .details-toggle {
        display: inline-flex;
        align-items: center;
        color: #007bff;
        cursor: pointer;
        user-select: none;
        font-weight: 500;
        margin-top: 4px;
    }

    .toggle-icon {
        margin-left: 4px;
        font-size: 0.75rem;
    }

    .query-details {
        margin-top: 10px;
        border-top: 1px solid #eee;
        padding-top: 10px;
        width: 100%;
    }

    .query-section {
        margin-bottom: 15px;
    }

    .query-section h4 {
        font-size: 0.9rem;
        margin-bottom: 8px;
        color: #555;
    }

    .sql-query {
        background-color: #f5f5f5;
        padding: 12px;
        border-radius: 4px;
        overflow-x: auto;
        font-family: 'Courier New', monospace;
        font-size: 0.9rem;
        line-height: 1.5;
        white-space: pre-wrap;
        word-wrap: break-word;
        word-break: break-word;
        max-width: 100%;
    }

    .inference-data {
        background-color: #f8f8f8;
        padding: 12px;
        border-radius: 4px;
        overflow-x: auto;
        font-family: 'Courier New', monospace;
        font-size: 0.85rem;
        line-height: 1.5;
        border: 1px solid #eaeaea;
        max-width: 100%;
        white-space: pre-wrap;
        word-wrap: break-word;
        word-break: break-word;
        color: #333;
    }

    .inference-data code {
        background: none;
        font-family: 'Courier New', monospace;
        color: #0a3253;
    }

    :deep(.sql-keyword) {
        color: #0033b3;
        font-weight: bold;
    }

    :deep(.sql-string) {
        color: #014325;
    }

    .query-result-table-container {
        overflow-x: auto;
        margin-top: 8px;
        max-width: 100%;
    }

    .query-result-table {
        width: 100%;
        border-collapse: collapse;
        font-size: 0.85rem;
        table-layout: auto;
    }

    .query-result-table th,
    .query-result-table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
        word-break: break-word;
        max-width: 250px;
        overflow-wrap: break-word;
    }

    .query-result-table th {
        background-color: #f2f2f2;
        font-weight: 600;
    }

    .query-result-table tr:nth-child(even) {
        background-color: #f9f9f9;
    }
</style>

// frontend/src/features/chat/ChatMessage.tsx
// 메시지 하나 (예전 components/ChatMessage.vue).
// 내 질문은 오른쪽에 글씨만, 답변은 말풍선 없이 본문으로. 답변 위에는 답을 만들며 부른 도구를 세로줄 목록으로 보여 준다.
import { memo, useMemo, useState } from 'react';
import agentLogo from '@/assets/agent-logo.png';
import type { ChatMessageType } from '@/types/chat';
import { parseMarkdown } from '@/utils/markdown';
import { toolSteps } from '@/utils/toolTrace';

// 마크다운 파서(utils/markdown.ts)는 HTML 특수 문자를 이미 escape한 글을 받는다.
// 답변에 들어 있는 <script> 같은 글자가 HTML로 실행되지 않게 먼저 바꾼다
const escapeHtml = (text: string) =>
    text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');

// 추론 데이터는 저장된 메시지에서는 JSON 문자열, 방금 받은 답변에서는 객체다. 보기 좋게 들여 쓴 글로 바꾼다
const prettyJson = (value: unknown): string => {
    try {
        const parsed = typeof value === 'string' ? JSON.parse(value) : value;
        return JSON.stringify(parsed, null, 2);
    } catch {
        return String(value);
    }
};

// 저장된 메시지의 쿼리 결과도 JSON 문자열이다
const rowsOf = (value: unknown): Record<string, unknown>[] => {
    if (Array.isArray(value)) return value;
    if (typeof value === 'string') {
        try {
            const parsed = JSON.parse(value);
            return Array.isArray(parsed) ? parsed : [];
        } catch {
            return [];
        }
    }
    return [];
};

function ChatMessageView({ message }: { message: ChatMessageType }) {
    const [showDetails, setShowDetails] = useState(false);
    const isUser = message.sender === 'user';
    const steps = useMemo(() => (isUser ? [] : toolSteps(message.inference)), [isUser, message.inference]);
    // 타이핑 중이면 지금까지 보여 준 만큼만 (빈 글자일 때 전체가 잠깐 보이지 않게)
    const shownText = message.animationState === 'typing' ? (message.displayText ?? '') : message.text;
    const html = useMemo(() => parseMarkdown(escapeHtml(shownText || '')), [shownText]);
    const rows = useMemo(() => rowsOf(message.query_result), [message.query_result]);
    const hasMeta = !isUser && (message.elapsed_time || message.inference);

    return (
        <div
            className={`message ${isUser ? 'user-message' : 'bot-message'}${
                message.animationState === 'appear' ? ' appear-animation' : ''
            }`}
        >
            {!isUser ? (
                <div className="message-avatar" aria-hidden="true">
                    <img src={agentLogo} alt="" />
                </div>
            ) : null}

            <div className="message-body">
                {steps.length > 0 ? (
                    // 실패는 색이 아니라 모양(— 와 굵기)으로 구분한다
                    <ol className="tool-trace" aria-label="사용한 도구">
                        {steps.map((step, index) => (
                            <li key={index} className={`tool-step${step.failed ? ' failed' : ''}`} title={step.name}>
                                <span className="tool-step-title">
                                    {step.failed ? '—' : '✓'} {step.label}
                                    {step.failed ? ' — 실패' : ''}
                                </span>
                                {step.detail ? <span className="tool-step-detail">{step.detail}</span> : null}
                                {step.error ? <span className="tool-step-detail tool-step-error">{step.error}</span> : null}
                            </li>
                        ))}
                    </ol>
                ) : null}

                {message.isTyping ? (
                    <div className="typing-indicator" role="status" aria-label="답변을 만드는 중">
                        <span className="dot" />
                        <span className="dot" />
                        <span className="dot" />
                    </div>
                ) : (
                    <div className="message-content markdown-content" dangerouslySetInnerHTML={{ __html: html }} />
                )}

                {hasMeta ? (
                    <div className="query-metadata">
                        {message.elapsed_time ? <span className="elapsed-time">실행 시간 {message.elapsed_time}</span> : null}
                        <button type="button" className="details-toggle" onClick={() => setShowDetails((v) => !v)}>
                            {showDetails ? '간략히 보기 ▲' : '자세히 보기 ▼'}
                        </button>

                        {showDetails ? (
                            <div className="query-details">
                                {message.query_string ? (
                                    <div className="query-section">
                                        <h4>SQL 쿼리</h4>
                                        <pre className="query-code">{message.query_string}</pre>
                                    </div>
                                ) : null}

                                {rows.length > 0 ? (
                                    <div className="query-section">
                                        <h4>쿼리 결과</h4>
                                        <div className="markdown-table-container">
                                            <table className="markdown-table">
                                                <thead>
                                                    <tr>
                                                        {Object.keys(rows[0]).map((key) => (
                                                            <th key={key}>{key}</th>
                                                        ))}
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {rows.map((row, rowIndex) => (
                                                        <tr key={rowIndex}>
                                                            {Object.entries(row).map(([key, value]) => (
                                                                <td key={key}>
                                                                    {typeof value === 'string'
                                                                        ? value.replace(/\\n/g, ' ')
                                                                        : String(value)}
                                                                </td>
                                                            ))}
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                ) : null}

                                {message.inference ? (
                                    <div className="query-section">
                                        <h4>추론 데이터</h4>
                                        <pre className="query-code">{prettyJson(message.inference)}</pre>
                                    </div>
                                ) : null}
                            </div>
                        ) : null}
                    </div>
                ) : null}
            </div>
        </div>
    );
}

// 타이핑 중인 답변 하나가 바뀔 때 다른 메시지는 다시 그리지 않는다
export const ChatMessage = memo(ChatMessageView);
